/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Programa creado por Isaac Yahel Luna Hernandez
package Tienda;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ivanvalle_
 */
public class Actualizar extends javax.swing.JFrame {

    Mensajes cmensaje = new Mensajes();
    Operaciones opera = new Operaciones();
    Ajuste aju = new Ajuste();
    Color PanelOpcionColor;
    Color FondoOpcionColor;
    Color colorpordefectofondo = new Color(215, 235, 235);
    Color colorpordefectobarra = new Color(39, 77, 96);
    Inventario inventario = new Inventario();

    ArrayList<String[]> categoria = new ArrayList<>();
    ArrayList<String[]> provedor = new ArrayList<>();
    ArrayList<String[]> productos = new ArrayList<>();

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
        this.setLocationRelativeTo(null);
        PanelOpcionColor = aju.mandarfechaycolores(2);
        FondoOpcionColor = aju.mandarfechaycolores(3);
        jBBarra.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        jPanel5.setBackground(PanelOpcionColor);
        try {
            productos = opera.Consultar(6);
            categoria = opera.Consultar(0);
            provedor = opera.Consultar(7);
            inventario.contruir_combo(categoria, jComboBoxCategoria);
            inventario.contruir_combo(provedor, jComboBoxProveedor);
//            mostrar_tabla();
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPFONDO = new javax.swing.JPanel();
        jComboBoxpProducto = new javax.swing.JComboBox<>();
        jBBarra = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPrecioV = new javax.swing.JTextField();
        jTextFieldPrecioC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPCatego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonCategoria = new javax.swing.JRadioButton();
        jRadioButtonProveedor = new javax.swing.JRadioButton();
        jPProvedo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxProveedor = new javax.swing.JComboBox<>();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPFONDO.setBackground(new java.awt.Color(215, 235, 235));
        jPFONDO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPFONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPFONDO.add(jComboBoxpProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jBBarra.setBackground(new java.awt.Color(39, 77, 96));
        jBBarra.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBBarra.setForeground(new java.awt.Color(255, 255, 255));
        jBBarra.setText("Actualizar");
        jBBarra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jBBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBarraActionPerformed(evt);
            }
        });
        jPFONDO.add(jBBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 230, 30));

        jPanel5.setBackground(new java.awt.Color(39, 77, 96));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Producto");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPFONDO.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Producto ");
        jPFONDO.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 90, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-retroceso.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setText("Precio venta:");
        jPFONDO.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTextFieldPrecioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioVActionPerformed(evt);
            }
        });
        jPFONDO.add(jTextFieldPrecioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, -1));

        jTextFieldPrecioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioCActionPerformed(evt);
            }
        });
        jPFONDO.add(jTextFieldPrecioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 230, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Precio compra:");
        jPFONDO.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPCatego.setBackground(new java.awt.Color(39, 77, 96));
        jPCatego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPCategoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria ");

        javax.swing.GroupLayout jPCategoLayout = new javax.swing.GroupLayout(jPCatego);
        jPCatego.setLayout(jPCategoLayout);
        jPCategoLayout.setHorizontalGroup(
            jPCategoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCategoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );
        jPCategoLayout.setVerticalGroup(
            jPCategoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCategoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPFONDO.add(jPCatego, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 20));

        buttonGroup1.add(jRadioButtonCategoria);
        jPFONDO.add(jRadioButtonCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        buttonGroup1.add(jRadioButtonProveedor);
        jPFONDO.add(jRadioButtonProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jPProvedo.setBackground(new java.awt.Color(39, 77, 96));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Proveedor");

        javax.swing.GroupLayout jPProvedoLayout = new javax.swing.GroupLayout(jPProvedo);
        jPProvedo.setLayout(jPProvedoLayout);
        jPProvedoLayout.setHorizontalGroup(
            jPProvedoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProvedoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(22, 22, 22))
        );
        jPProvedoLayout.setVerticalGroup(
            jPProvedoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProvedoLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPFONDO.add(jPProvedo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 20));

        jComboBoxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProveedorActionPerformed(evt);
            }
        });
        jPFONDO.add(jComboBoxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, -1));

        jPFONDO.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, -1));

        jButton1.setBackground(new java.awt.Color(215, 235, 235));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPFONDO.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        jPFONDO.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void buscar() throws SQLException {
        jComboBoxpProducto.removeAllItems();
        if (jRadioButtonCategoria.isSelected()) {
            for (int i = 0; i < productos.size(); i++) {
                String fila[] = productos.get(i);
                if (fila[5].equals(inventario.obtener_indice(categoria, jComboBoxCategoria)+"")) {
                    jComboBoxpProducto.addItem(fila[1]);
                }
            }
        } else if (jRadioButtonProveedor.isSelected()) {
            for (int i = 0; i < productos.size(); i++) {
                String fila[] = productos.get(i);
                if (fila[5].equals(inventario.obtener_indice(provedor, jComboBoxProveedor)+"")) {
                    jComboBoxpProducto.addItem(fila[1]);
                }

            }
        }
    }
    private void jBBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBarraActionPerformed
       int id=0;
        if (jComboBoxpProducto.getItemCount() > 0 && jComboBoxpProducto.getSelectedItem() != null) {
    // Encontrar el ID del producto seleccionado
    for (String[] fila : productos) {
        if (fila[1].equals(jComboBoxpProducto.getSelectedItem().toString())) {
            id = Integer.parseInt(fila[0]);
            break;
        }
    }
    // Validar y actualizar precios
    try {
        int precioCompra = Integer.parseInt(jTextFieldPrecioC.getText());
        int precioVenta = Integer.parseInt(jTextFieldPrecioV.getText());
        if (precioCompra > 0 && precioVenta > 0 && precioCompra < precioVenta) {
            opera.Actualizar(id, "producto", "precio_venta", String.valueOf(precioVenta));
            opera.Actualizar(id, "producto", "precio_compra", String.valueOf(precioCompra));
            cmensaje.mensaje("Producto añadido");
        } else {
            cmensaje.mensaje_error("Error, revise las cantidades.");
        }
    } catch (NumberFormatException e) {
        cmensaje.mensaje_error("Por favor, ingrese valores numéricos válidos en los precios.");
    }
} else {
    cmensaje.mensaje_error("Error, no se ha seleccionado ningún producto.");
}

    }//GEN-LAST:event_jBBarraActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Inventario newframe = new Inventario();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextFieldPrecioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioVActionPerformed

    private void jTextFieldPrecioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioCActionPerformed

    private void jPCategoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPCategoMouseClicked
        //AQUI
    }//GEN-LAST:event_jPCategoMouseClicked

    private void jComboBoxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProveedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cmensaje.mensaje("Busqueda exitosa");
        try {
            System.out.println("aasdsad");
            buscar();
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBBarra;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxProveedor;
    private javax.swing.JComboBox<String> jComboBoxpProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCatego;
    private javax.swing.JPanel jPFONDO;
    private javax.swing.JPanel jPProvedo;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonCategoria;
    private javax.swing.JRadioButton jRadioButtonProveedor;
    private javax.swing.JTextField jTextFieldPrecioC;
    private javax.swing.JTextField jTextFieldPrecioV;
    // End of variables declaration//GEN-END:variables
}
