/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Programa creado por Isaac Yahel Luna Hernandez
package Tienda;

import java.awt.Color;
import java.util.ArrayList;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author Ivanvalle_
 */
public class AgregarProducto extends javax.swing.JFrame {
//*************************Parametros**********************************//
//***********************************************************//

    Mensajes cmensaje = new Mensajes();
    Operaciones opera = new Operaciones();
    Ajuste aju = new Ajuste();
    Inventario inventario = new Inventario();
    Color PanelOpcionColor;
    Color FondoOpcionColor;
    Color colorpordefectofondo = new Color(215, 235, 235);
    Color colorpordefectobarra = new Color(39, 77, 96);

    ArrayList<String[]> productos = new ArrayList<>();
    ArrayList<String[]> categoria = new ArrayList<>();
    ArrayList<String[]> provedor = new ArrayList<>();

//**************************Fin de parametros*********************************//
//***********************************************************//
    /**
     * Creates new form Agrepro
     */
    public AgregarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        PanelOpcionColor = aju.mandarfechaycolores(2);
        FondoOpcionColor = aju.mandarfechaycolores(3);
        jBBarra.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        jPanel4.setBackground(PanelOpcionColor);
        jPanel5.setBackground(PanelOpcionColor);

        try {
            productos = opera.Consultar(6);
            categoria = opera.Consultar(0);
            provedor = opera.Consultar(7);
            inventario.contruir_combo(categoria, jComboBoxCategoria);
            inventario.contruir_combo(provedor, jComboBoxProveedor);
        } catch (SQLException ex) {
            Logger.getLogger(AgregarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFONDO = new javax.swing.JPanel();
        jTextNombre = new javax.swing.JTextField();
        jBBarra = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextPVenta = new javax.swing.JTextField();
        jTextPCompra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxProveedor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPFONDO.setBackground(new java.awt.Color(215, 235, 235));
        jPFONDO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPFONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jPFONDO.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 230, -1));

        jBBarra.setBackground(new java.awt.Color(39, 77, 96));
        jBBarra.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBBarra.setForeground(new java.awt.Color(255, 255, 255));
        jBBarra.setText("Añadir producto");
        jBBarra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jBBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBarraActionPerformed(evt);
            }
        });
        jPFONDO.add(jBBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 230, 30));

        jPanel4.setBackground(new java.awt.Color(39, 77, 96));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categoria ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPFONDO.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, 20));

        jPanel5.setBackground(new java.awt.Color(39, 77, 96));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Proveedor");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPFONDO.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nuevo Producto ");
        jPFONDO.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 170, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-retroceso.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre:");
        jPFONDO.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Código:");
        jPFONDO.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });
        jPFONDO.add(jTextCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Precio venta:");
        jPFONDO.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jTextPVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPVentaActionPerformed(evt);
            }
        });
        jPFONDO.add(jTextPVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 230, -1));

        jTextPCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPCompraActionPerformed(evt);
            }
        });
        jPFONDO.add(jTextPCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 230, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio compra:");
        jPFONDO.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jPFONDO.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 110, -1));

        jComboBoxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProveedorActionPerformed(evt);
            }
        });
        jPFONDO.add(jComboBoxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBarraActionPerformed

        if (cmensaje.mensaje_confirmacion("Desea añadir el producto?", "Procesando...", "Error, elemento desechado")) {
            //comparar elementos
            boolean opcion = false;
            String lista[] = new String[6];
            for (int i = 0; i < productos.size(); i++) {
                String fila[] = productos.get(i);
                if (fila[0].equals(jTextCodigo.getText()) || fila[1].equals(jTextNombre.getText())) {
                    cmensaje.mensaje_error("Valores duplicados, revise codigo o nombre");
                    opcion = false;
                    break;
                } else {
                    if (jTextPCompra.getText().equals(jTextPVenta.getText())) {
                        cmensaje.mensaje_error("El precio de compra no puede ser mayor ni igual al de venta");
                        opcion = false;
                        break;
                    } else {
                        //armar lista
                        lista[0] = jTextCodigo.getText();
                        lista[1] = jTextNombre.getText();
                        lista[2] = jTextPVenta.getText();
                        lista[3] = jTextPCompra.getText();
                        try {
                            lista[4] = "" + inventario.obtener_indice(categoria, jComboBoxCategoria);
                            lista[5] = "" + inventario.obtener_indice(provedor, jComboBoxProveedor);
                            opcion = true;
                        } catch (SQLException ex) {
                            Logger.getLogger(AgregarProducto.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
            }
            try {
                if (opcion) {
                    opera.Insertar_Producto(lista);
                    jTextCodigo.setText("");
                    jTextNombre.setText("");
                    jTextPCompra.setText("");
                    jTextPVenta.setText("");
                    cmensaje.mensaje("Producto añadido con exito");

                }
            } catch (SQLException ex) {
                Logger.getLogger(AgregarProducto.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jBBarraActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Inventario newframe = new Inventario();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jTextPVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPVentaActionPerformed

    private void jTextPCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPCompraActionPerformed

    private void jComboBoxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBarra;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxProveedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPFONDO;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPCompra;
    private javax.swing.JTextField jTextPVenta;
    // End of variables declaration//GEN-END:variables
}
