/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Programa creado por Isaac Yahel Luna Hernandez
package Tienda;

import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Ivanvalle_
 */
public class Ajuste extends javax.swing.JFrame {
//*************************Parametros**********************************//
//***********************************************************//

    Mensajes cmensaje = new Mensajes();
    Operaciones opera = new Operaciones();

    Color PanelOpcionColor;
    Color FondoOpcionColor;
    Color colorpordefectobarra = new Color(215, 235, 235);
    Color colorpordefectofondo = new Color(39, 77, 96);
    String usuario;
//**************************Fin de parametros*********************************//
//***********************************************************//

    /**
     * Creates new form Ajuste
     */
    public Ajuste() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            usuario = opera.conseguir_color(1);
        } catch (SQLException ex) {
            Logger.getLogger(Ajuste.class.getName()).log(Level.SEVERE, null, ex);
        }
        PanelOpcionColor = mandarfechaycolores(2);
        FondoOpcionColor = mandarfechaycolores(3);
        jPBARRA.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        jPanelseleccion.setBackground(FondoOpcionColor);
        jPanel1.setBackground(PanelOpcionColor);

    }

    public Color mandarfechaycolores(int numero) {
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        String color = null;

        try {
            color = opera.conseguir_color(numero);
        } catch (SQLException ex) {
            Logger.getLogger(Ajuste.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] valores = color.split(",");
        int r = Integer.parseInt(valores[0]); // Componente rojo
        int g = Integer.parseInt(valores[1]); // Componente verde
        int b = Integer.parseInt(valores[2]); // Componente azul
        // Crear el color
        Color retornacolor = new Color(r, g, b);

        // Formatear la fecha
        String fecha = fechaActual.format(formato);
        jLFecha.setText(fecha + "");
        return retornacolor;

    }

    public void colorear(Color color1, Color color2, String actualiza, JPanel panel) throws SQLException {
        // SELECCIONAR COLOR 1

        color1 = Color.BLACK;

        color1 = JColorChooser.showDialog(this, "SELECIONA UN COLOR", color1);
        if (color1 == null) {
            color1 = color2;
        }
        //this.color1 = color1;
        panel.setBackground(color1);
        int r = color1.getRed();
        int g = color1.getGreen();
        int b = color1.getBlue();

        // Convertir a formato "R,G,B"
        String colorEnTexto = "'" + r + "," + g + "," + b + "'";
        opera.Actualizar(1, "Usuario", actualiza, colorEnTexto);

        PanelOpcionColor = mandarfechaycolores(2);
        FondoOpcionColor = mandarfechaycolores(3);
        jPBARRA.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        jPanelseleccion.setBackground(FondoOpcionColor);
        jPanel1.setBackground(PanelOpcionColor);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFONDO = new javax.swing.JPanel();
        jPBARRA = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelseleccion = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLbarra = new javax.swing.JLabel();
        jLfondo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLFecha = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPFONDO.setBackground(new java.awt.Color(215, 235, 235));
        jPFONDO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPFONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBARRA.setBackground(new java.awt.Color(39, 77, 96));
        jPBARRA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas-de-verificacion.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas (1).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-dinero (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verificar (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Inicio");
        jPBARRA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa (4).png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inventario");
        jPBARRA.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Perdidas");
        jPBARRA.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Compras");
        jPBARRA.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jPanelseleccion.setBackground(new java.awt.Color(215, 235, 235));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel15.setText("Ajustes");

        javax.swing.GroupLayout jPanelseleccionLayout = new javax.swing.GroupLayout(jPanelseleccion);
        jPanelseleccion.setLayout(jPanelseleccionLayout);
        jPanelseleccionLayout.setHorizontalGroup(
            jPanelseleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelseleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelseleccionLayout.setVerticalGroup(
            jPanelseleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelseleccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPBARRA.add(jPanelseleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 130, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ventas");
        jPBARRA.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grafico-de-torta (1).png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 264, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Reportes");
        jPBARRA.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/q3.png"))); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPBARRA.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 130));

        jPFONDO.add(jPBARRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 550));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion-de-usuario.png"))); // NOI18N
        jLabel1.setText("Cerrar sesión");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 160, -1));

        jLbarra.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLbarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bote-de-pintura.png"))); // NOI18N
        jLbarra.setText("Cambiar color de barra");
        jLbarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbarraMouseClicked(evt);
            }
        });
        jPFONDO.add(jLbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 190, -1));

        jLfondo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bote-de-pintura.png"))); // NOI18N
        jLfondo.setText("Cambiar color de fondo");
        jLfondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfondoMouseClicked(evt);
            }
        });
        jPFONDO.add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recargar.png"))); // NOI18N
        jLabel2.setText(" Cambiar Contraseña");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFecha.setBackground(new java.awt.Color(255, 255, 255));
        jLFecha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLFecha.setText("02/12/2024");
        jPanel1.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        jPFONDO.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 80, 20));

        jLabel19.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel19.setText("?");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 20, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.PREFERRED_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean contraseña(JFrame Frame) {

        try {
            usuario = opera.conseguir_color(1);
        } catch (SQLException ex) {
            Logger.getLogger(Ajuste.class.getName()).log(Level.SEVERE, null, ex);
        }
        String contraseña = cmensaje.mensaje_de_pregunta("Ingrese contraseña:");
        if (contraseña == null || contraseña.isEmpty()) {
            cmensaje.mensaje_error("Accion cancelada por el usuario");
            return false; // Salir del método si la contraseña es nula o vacía
        }

        if (contraseña.equals(usuario) && contraseña != null) {
            Frame.setVisible(true);
            dispose();
            return true;
        } else {

            cmensaje.mensaje_error("Error contraseña incorrecta");
        return false;
        }
    }

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Inventario newframe = new Inventario();
        if(contraseña(newframe)== true){
            dispose();   
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        Ventas newframe = new Ventas();
        if(contraseña(newframe)== true){
            dispose();   
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        Perdidas newframe = new Perdidas();
        if(contraseña(newframe)== true){
            dispose();   
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        Comprar newframe = new Comprar();
        if(contraseña(newframe)== true){
            dispose();   
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Inicio newframe = new Inicio();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Reportes newframe = new Reportes();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        Ajuste newframe = new Ajuste();
        newframe.setVisible(true);
        jPBARRA.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLbarraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbarraMouseClicked
        try {
            colorear(PanelOpcionColor, colorpordefectofondo, "color_barra", jPBARRA);

        } catch (SQLException ex) {
            Logger.getLogger(Ajuste.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLbarraMouseClicked

    private void jLfondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfondoMouseClicked
        try {
            colorear(FondoOpcionColor, colorpordefectobarra, "color_fondo", jPFONDO);
            jPanelseleccion.setBackground(FondoOpcionColor);
        } catch (SQLException ex) {
            Logger.getLogger(Ajuste.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLfondoMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        String actual = cmensaje.mensaje_de_pregunta("Ingrese la contrase actual:");
        if (actual.equals(usuario)) {
            String contraseña = cmensaje.mensaje_de_pregunta("Ingrese la nueva contraseña: ");
            String confirma = cmensaje.mensaje_de_pregunta("Confirme la contraseña: ");

            if (contraseña.equals(confirma) || contraseña.equals("1234")) {

                cmensaje.mensaje("Su cambio de contraseña se ha realizado correctamente");
                opera.Actualizar(1, "usuario", "usuario_contraseña", contraseña);

            } else {
                cmensaje.mensaje_error("Las contraseñas no coinciden, vuelta a intentarlo");
            }
        } else {
            cmensaje.mensaje_error("Contraseña incorrecta");
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        cmensaje.mensaje("Si tienes alguna duda con tu inicio, "
                + "puede checar el manual de usuario, punto 7.-Ajustes");
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajuste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbarra;
    private javax.swing.JLabel jLfondo;
    private javax.swing.JPanel jPBARRA;
    private javax.swing.JPanel jPFONDO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelseleccion;
    // End of variables declaration//GEN-END:variables
}
