/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Programa creado por Isaac Yahel Luna Hernandez
package Tienda;

import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivanvalle_
 */

public class Comprar extends javax.swing.JFrame {
//*************************Parametros**********************************//
//***********************************************************//

    Mensajes cmensaje = new Mensajes();
    Ventas mov = new Ventas();
    ArrayList<String[]> cuenta = new ArrayList<>();
    Operaciones opera = new Operaciones();
    Ajuste aju = new Ajuste();
    String color;
    Color PanelOpcionColor;
    Color FondoOpcionColor;
    Color colorpordefectofondo = new Color(215, 235, 235);
    Color colorpordefectobarra = new Color(39, 77, 96);
    String usuario;

//**************************Fin de parametros*********************************//
//***********************************************************//
    /**
     * Creates new form Comp
     */
    public Comprar() {
        initComponents();
        try {
            usuario = opera.conseguir_color(1);
        } catch (SQLException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        }
        PanelOpcionColor = aju.mandarfechaycolores(2);
        FondoOpcionColor = aju.mandarfechaycolores(3);
        jPBARRA.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        jPComp.setBackground(FondoOpcionColor);
        jPanel1.setBackground(PanelOpcionColor);
        this.setLocationRelativeTo(null);
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Formatear la fecha
        String fecha = fechaActual.format(formato);
        jLFecha.setText(fecha + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFONDO = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLFecha = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jBOK1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBActualizar = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();
        jBPerdida = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPBARRA = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPComp = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPFONDO.setBackground(new java.awt.Color(215, 235, 235));
        jPFONDO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPFONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFecha.setBackground(new java.awt.Color(255, 255, 255));
        jLFecha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLFecha.setText("02/12/2024");
        jPanel1.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 80, -1));

        jPFONDO.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 80, 20));

        jTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigoActionPerformed(evt);
            }
        });
        jPFONDO.add(jTCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 60, 280, -1));

        jBOK1.setBackground(new java.awt.Color(215, 235, 235));
        jBOK1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBOK1.setText("Añadir");
        jBOK1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBOK1MouseClicked(evt);
            }
        });
        jBOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOK1ActionPerformed(evt);
            }
        });
        jPFONDO.add(jBOK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPFONDO.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 430, 200));

        jBActualizar.setBackground(new java.awt.Color(215, 235, 235));
        jBActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBActualizar.setText("Actualizar");
        jBActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBActualizarMouseClicked(evt);
            }
        });
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });
        jPFONDO.add(jBActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, 30));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/procesamiento-de-datos.png"))); // NOI18N
        jPFONDO.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jBEliminar.setBackground(new java.awt.Color(215, 235, 235));
        jBEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBEliminar.setText("Eliminar Producto");
        jBEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBEliminarMouseClicked(evt);
            }
        });
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPFONDO.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 180, -1));

        jBPerdida.setBackground(new java.awt.Color(215, 235, 235));
        jBPerdida.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBPerdida.setText("Confirmar Compra");
        jBPerdida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPerdidaMouseClicked(evt);
            }
        });
        jBPerdida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPerdidaActionPerformed(evt);
            }
        });
        jPFONDO.add(jBPerdida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 180, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel35.setText("Total");
        jPFONDO.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));
        jPFONDO.add(jLTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 220, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Registro de Compras");
        jPFONDO.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jPBARRA.setBackground(new java.awt.Color(39, 77, 96));
        jPBARRA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas-de-verificacion.png"))); // NOI18N
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas (1).png"))); // NOI18N
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-dinero (1).png"))); // NOI18N
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verificar.png"))); // NOI18N
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grafico-de-torta (1).png"))); // NOI18N
        jLabel51.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel8AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 264, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Inicio");
        jPBARRA.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 30, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa (4).png"))); // NOI18N
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Inventario");
        jPBARRA.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Ventas");
        jPBARRA.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Perdidas");
        jPBARRA.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Reportes");
        jPBARRA.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jPComp.setBackground(new java.awt.Color(215, 235, 235));

        jLabel58.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel58.setText("Compras");

        javax.swing.GroupLayout jPCompLayout = new javax.swing.GroupLayout(jPComp);
        jPComp.setLayout(jPCompLayout);
        jPCompLayout.setHorizontalGroup(
            jPCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCompLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(28, 28, 28))
        );
        jPCompLayout.setVerticalGroup(
            jPCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCompLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addContainerGap())
        );

        jPBARRA.add(jPComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 130, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ajustes");
        jPBARRA.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/q3.png"))); // NOI18N
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPBARRA.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 130));

        jPFONDO.add(jPBARRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 550));

        jLabel20.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel20.setText("?");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 20, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Ajuste newframe = new Ajuste();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Inicio newframe = new Inicio();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Reportes newframe = new Reportes();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel8AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8AncestorAdded

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Comprar newframe = new Comprar();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Perdidas newframe = new Perdidas();
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Ventas newframe = new Ventas();
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Inventario newframe = new Inventario();
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jBPerdidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPerdidaActionPerformed
        // TODO add your handling code here:
        mov.actualizar(cuenta, jTable1, jLTotal);
        if (cmensaje.mensaje_confirmacion("¿Estás seguro de confirmar esta compra?", "Compra confirmada", "Compra fallida")) {
            try {
                // TODO add your handling code here:
                boolean producto_descontado = true;
                ArrayList<String[]> productos = opera.Consultar(6); // Lista de productos en stock
                StringBuilder errores = new StringBuilder();       // Para acumular errores
                for (String[] fila : cuenta) {                     // Recorrer productos en cuenta
                    boolean encontrado = false;
                    for (String[] prod : productos) {
                        if (fila[0].equals(prod[1])) { // Comparar códigos o identificadores
                            encontrado = true;
                            int stockActual = Integer.parseInt(prod[2]);
                            int cantidadSolicitada = Integer.parseInt(fila[1]);
                            if (cantidadSolicitada<0) {
                                errores.append("Error: No hay suficiente stock de ")
                                        .append(prod[1])
                                        .append(". Stock actual: ")
                                        .append(stockActual)
                                        .append(", solicitado: ")
                                        .append(cantidadSolicitada)
                                        .append(".\n");
                                producto_descontado = false;
                            }
                            break; // Producto encontrado, salir del bucle
                        }
                    }
                    if (!encontrado) {
                        errores.append("Error: Producto no encontrado en stock: ")
                                .append(fila[0])
                                .append(".\n");
                        producto_descontado = false;
                    }
                }

// Mostrar errores acumulados si los hay
                if (errores.length() > 0) {
                    cmensaje.mensaje_error(errores.toString());
                }

                if (producto_descontado) {
                opera.Insertar_venta("compra", cuenta, mov.mandar_total(jLTotal, cuenta));
                Comprar newframe = new Comprar();
                newframe.setVisible(true);
                dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jBPerdidaActionPerformed

    private void jBPerdidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPerdidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPerdidaMouseClicked

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        cmensaje.mensaje_confirmacion("¿Estás seguro de eliminar el producto de la compra?", "Accion confirmada", "Accion fallida");
        mov.eliminar(jTable1, cuenta, jLTotal);
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarMouseClicked

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        cmensaje.mensaje("Tabla actualizada");
        mov.actualizar(cuenta, jTable1, jLTotal);
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBActualizarMouseClicked

    private void jBOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOK1ActionPerformed
        cmensaje.mensaje("Producto añadido");
        try {
            mov.transaccion(4, jTable1, jTCodigo.getText(), cuenta, jLTotal);
            jTCodigo.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBOK1ActionPerformed

    private void jBOK1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBOK1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOK1MouseClicked

    private void jTCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodigoActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        cmensaje.mensaje("Si tienes alguna duda con tu inicio, "
                + "puede checar el manual de usuario, punto 5.-Compra");
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBOK1;
    private javax.swing.JButton jBPerdida;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPBARRA;
    private javax.swing.JPanel jPComp;
    private javax.swing.JPanel jPFONDO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
