/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Programa creado por Isaac Yahel Luna Hernandez
package Tienda;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Ivanvalle_
 */
public class Inicio extends javax.swing.JFrame {
Mensajes cmensaje = new Mensajes();
    Reportes repo = new Reportes();
    Operaciones opera = new Operaciones();
    Ajuste aju = new Ajuste();
    String color;
    Color PanelOpcionColor;
    Color FondoOpcionColor;
    Color colorpordefectofondo = new Color (215,235,235);
    Color colorpordefectobarra = new Color(39,77,96);

    ArrayList<String[]> detalle_venta= new ArrayList<>();
    ArrayList<String[]> detalle_perdida= new ArrayList<>();
    ArrayList<String[]> detalle_compra= new ArrayList<>();
    ArrayList<String[]>  productos= new ArrayList<>();
    String usuario;
        int total[]= new int[3];
    
    
    public Inicio() {
        initComponents();
    try {
        usuario = opera.conseguir_color(3);
    } catch (SQLException ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
    }
        PanelOpcionColor = aju.mandarfechaycolores(2);
        FondoOpcionColor = aju.mandarfechaycolores(3);
        jPBARRA.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        jPInici.setBackground(FondoOpcionColor);
        jPanel1.setBackground(PanelOpcionColor);
        jList1.setBackground(FondoOpcionColor);
        
         this.setLocationRelativeTo(null); 
          LocalDate fechaActual = LocalDate.now();
          DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Formatear la fecha
        String fecha = fechaActual.format(formato);
        jLFecha.setText(fecha+"");
    try {
        generar_datos();
        generar_lista();
        mostrar_grafica(jPbaraas, "2", total, "Detalle:", "Compras, Perdidas y Venta");
    } catch (SQLException ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPFONDO = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPBARRA = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPInici = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPbaraas = new javax.swing.JPanel();
        Bgraficapastel = new javax.swing.JButton();
        jBgraficasbarra = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLFecha = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPFONDO.setBackground(new java.awt.Color(215, 235, 235));
        jPFONDO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPFONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Grafica de Perdidas, Compras y Ventas");
        jPFONDO.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 370, -1));

        jPBARRA.setBackground(new java.awt.Color(39, 77, 96));
        jPBARRA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas-de-verificacion.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas (1).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-dinero (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verificar (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grafico-de-torta (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 264, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setText("Inicio");
        jPBARRA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa (3).png"))); // NOI18N
        jPBARRA.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inventario");
        jPBARRA.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ventas");
        jPBARRA.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Perdidas");
        jPBARRA.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Compras");
        jPBARRA.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Reportes");
        jPBARRA.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jPInici.setBackground(new java.awt.Color(215, 235, 235));

        javax.swing.GroupLayout jPIniciLayout = new javax.swing.GroupLayout(jPInici);
        jPInici.setLayout(jPIniciLayout);
        jPIniciLayout.setHorizontalGroup(
            jPIniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPIniciLayout.setVerticalGroup(
            jPIniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPBARRA.add(jPInici, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 40));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Ajustes");
        jPBARRA.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/q3.png"))); // NOI18N
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPBARRA.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 130));

        jPFONDO.add(jPBARRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 550));

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 2, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jPFONDO.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 520, 170));

        jPbaraas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPbaraas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPFONDO.add(jPbaraas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 450, 270));

        Bgraficapastel.setText("Graficar Pastel");
        Bgraficapastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgraficapastelActionPerformed(evt);
            }
        });
        jPFONDO.add(Bgraficapastel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));

        jBgraficasbarra.setText("Graficar Barras");
        jBgraficasbarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgraficasbarraActionPerformed(evt);
            }
        });
        jPFONDO.add(jBgraficasbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFecha.setBackground(new java.awt.Color(255, 255, 255));
        jLFecha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLFecha.setText("02/12/2024");
        jPanel1.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPFONDO.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 80, 20));

        jLabel36.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel36.setText("?");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 20, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel16.setText("TOP 5 DE PRODUCTOS DEL MES ");
        jPFONDO.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 370, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//***************************Comienzo de codigo *********************************************//
  public void generar_lista() {
    // Crear una lista para consolidar los productos
    ArrayList<String[]> productosConsolidados = new ArrayList<>();

    // Consolidar los productos y sumar cantidades
    for (String[] venta : detalle_venta) {
        String idProducto = venta[4]; // ID del producto
        int cantidadVendida = Integer.parseInt(venta[1]); // Cantidad vendida

        // Buscar si el producto ya está en la lista consolidada
        boolean encontrado = false;
        for (String[] producto : productosConsolidados) {
            if (producto[0].equals(idProducto)) {
                // Si existe, sumar la cantidad vendida
                producto[1] = String.valueOf(Integer.parseInt(producto[1]) + cantidadVendida);
                encontrado = true;
                break;
            }
        }

        // Si no está en la lista, agregarlo como un nuevo producto
        if (!encontrado) {
            productosConsolidados.add(new String[]{idProducto, String.valueOf(cantidadVendida)});
        }
    }

    // Cambiar los IDs de los productos por sus nombres
    for (String[] producto : productosConsolidados) {
        for (String[] datosProducto : productos) {
            if (producto[0].equals(datosProducto[0])) {
                producto[0] = datosProducto[1]; // Reemplazar ID con nombre
                break;
            }
        }
    }

    // Ordenar la lista por cantidad vendida (de mayor a menor)
    productosConsolidados.sort((p1, p2) -> Integer.compare(Integer.parseInt(p2[1]), Integer.parseInt(p1[1])));

    // Asegurar que el modelo del JList sea DefaultListModel
    if (!(jList1.getModel() instanceof DefaultListModel)) {
        jList1.setModel(new DefaultListModel<>());
    }
    DefaultListModel<String> listModel = (DefaultListModel<String>) jList1.getModel();

    // Limpiar el modelo antes de agregar nuevos elementos
    listModel.clear();

    // Agregar los nombres de los 5 productos más vendidos al JList
    for (int i = 0; i < Math.min(5, productosConsolidados.size()); i++) {
        listModel.addElement(productosConsolidados.get(i)[0]); // Nombre del producto
    }
}



    public void generar_datos() throws SQLException{
        detalle_compra=opera.Consultar(2);
        detalle_perdida=opera.Consultar(3);
        detalle_venta=opera.Consultar(4);
       productos=opera.Consultar(6);
        for (int i = 0; i < detalle_compra.size(); i++) {
            String fila[]= detalle_compra.get(i);
            total[0]+=Integer.parseInt(fila[2]);
            
        }
        for (int i = 0; i < detalle_venta.size(); i++) {
            String fila[]= detalle_venta.get(i);
            total[1]+=Integer.parseInt(fila[2]);
            
        }
        for (int i = 0; i < detalle_perdida.size(); i++) {
            String fila[]= detalle_perdida.get(i);
            total[2]+=Integer.parseInt(fila[2]);
            
        }
    }  
    public void mostrar_grafica(JPanel panell, String opcion,int []datosgrafica, String a, String b) throws SQLException {
          
        panell.removeAll();
        panell.revalidate();

        if (opcion.equals("1")) {
            DefaultPieDataset datos = new DefaultPieDataset();
            // nombre valor 
                datos.setValue("Compras"+"", datosgrafica[0]);
                datos.setValue("Perdidas"+"", datosgrafica[1]);
                datos.setValue("Ventas"+"", datosgrafica[2]);
                
            JFreeChart grafico_circular = ChartFactory.createPieChart(
                    "Compras, Perdidas y Ventas", //nombre del grafico
                    datos, //datos
                    true, //nombre de las categorias
                    true, //herramientas
                    false //generacion de url
            );
            ChartPanel panel = new ChartPanel(grafico_circular); //
            panel.setMouseWheelEnabled(true);                             //para que se pueda mover la rueda del raton
            panel.setPreferredSize(new Dimension(400, 300));         //asignamos dimension
            panell.setLayout(new BorderLayout());
            panell.add(panel, BorderLayout.NORTH);
            pack();
        } else {
            DefaultCategoryDataset datos = new DefaultCategoryDataset();
                    
                
            datos.setValue(datosgrafica[0], a+ b+ "", "Compras"+"");
            datos.setValue(datosgrafica[1], a+ b+ "", "Perdidas"+"");
            datos.setValue(datosgrafica[2], a+ b+ "", "Ventas"+"");
            
                
            JFreeChart barras = ChartFactory.createBarChart3D
                    ("Compras, Perdidas y Ventas", //Nombre del grafico
                    "Total", //Nombre de las barras o columnas
                    "Cantidad $",
                    datos, //Datos del grafico
                    PlotOrientation.VERTICAL, //Orientacion
                    true, //barras individuales por color
                    true, //Texto emergente
                    false //url del grafico
            );
            ChartPanel panel = new ChartPanel(barras); //
            panel.setMouseWheelEnabled(true);                             //para que se pueda mover la rueda del raton
            panel.setPreferredSize(new Dimension(400, 300));         //asignamos dimension
            panell.setLayout(new BorderLayout());
            panell.add(panel, BorderLayout.NORTH);
            pack();

        }
        repaint();

    }
//****************************Fin de codigo*********************************************//
//**************************************************************************//
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
         Inventario newframe = new Inventario();
      if(aju.contraseña(newframe)== true){
            dispose();   
        }
      
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       Ventas newframe = new Ventas();
      if(aju.contraseña(newframe)== true){
            dispose();   
        }
      
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Perdidas newframe = new Perdidas();
      if(aju.contraseña(newframe)== true){
            dispose();   
        }
      
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
         Comprar newframe = new Comprar();
      if(aju.contraseña(newframe)== true){
            dispose();   
        }
      
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Reportes newframe = new Reportes();
      newframe.setVisible(true);
      dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
       Ajuste newframe = new Ajuste();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void BgraficapastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgraficapastelActionPerformed
    try {
        //        repo.mostrar_grafica(jPbaraas, "1");
        mostrar_grafica(jPbaraas, "1", total, "Detalle:", "Compras, Perdidas y Venta");
    } catch (SQLException ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_BgraficapastelActionPerformed

    private void jBgraficasbarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgraficasbarraActionPerformed
//        repo.mostrar_grafica(jPbaraas, "2");
    try {
        //        repo.mostrar_grafica(jPbaraas, "1");
        mostrar_grafica(jPbaraas, "2", total, "Detalle:", "Compras, Perdidas y Venta");
    } catch (SQLException ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_jBgraficasbarraActionPerformed

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        cmensaje.mensaje("Si tienes alguna duda con tu inicio, "
            + "puede checar el manual de usuario, punto 1.-Inicio");
    }//GEN-LAST:event_jLabel36MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bgraficapastel;
    private javax.swing.JButton jBgraficasbarra;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPBARRA;
    private javax.swing.JPanel jPFONDO;
    private javax.swing.JPanel jPInici;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPbaraas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
