/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Programa creado por Isaac Yahel Luna Hernandez
package Tienda;

import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivanvalle_
 */
public class Inventario extends javax.swing.JFrame {
//*************************Parametros**********************************//
//***********************************************************//

    Mensajes cmensaje = new Mensajes();
    Operaciones opera = new Operaciones();
    Ajuste aju = new Ajuste();
    String color;
    Color PanelOpcionColor;
    Color FondoOpcionColor;
    Color colorpordefectofondo = new Color(215, 235, 235);
    Color colorpordefectobarra = new Color(39, 77, 96);

    ArrayList<String[]> categoria = new ArrayList<>();
    ArrayList<String[]> provedor = new ArrayList<>();
    ArrayList<String[]> productos = new ArrayList<>();
String usuario;
//**************************Fin de parametros*********************************//
//***********************************************************//
    /**
     * Creates new form Inv
     */
    public Inventario() {
        initComponents();
        try {
            usuario = opera.conseguir_color(1);
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        PanelOpcionColor = aju.mandarfechaycolores(2);
        FondoOpcionColor = aju.mandarfechaycolores(3);
        jPBARRA.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        jPCatego.setBackground(PanelOpcionColor);
        jPProvedo.setBackground(PanelOpcionColor);
        jPInven.setBackground(FondoOpcionColor);
        jPanel1.setBackground(PanelOpcionColor);
        this.setLocationRelativeTo(null);
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        // Formatear la fecha
        String fecha = fechaActual.format(formato);
        jLFecha.setText(fecha + "");
        try {
            productos = opera.Consultar(6);
            categoria = opera.Consultar(0);
            provedor = opera.Consultar(7);
            contruir_combo(categoria, jComboBoxCategoria );
            contruir_combo(provedor, jComboBoxProveedor);
            mostrar_tabla();
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPFONDO = new javax.swing.JPanel();
        jPBARRA = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPInven = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxProveedor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jPCatego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPProvedo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLFecha = new javax.swing.JLabel();
        jBAgregar1 = new javax.swing.JButton();
        jRadioButtonProveedor = new javax.swing.JRadioButton();
        jRadioButtonCategoria = new javax.swing.JRadioButton();
        jBAgregar2 = new javax.swing.JButton();
        jBAgregar3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPFONDO.setBackground(new java.awt.Color(215, 235, 235));
        jPFONDO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPFONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBARRA.setBackground(new java.awt.Color(39, 77, 96));
        jPBARRA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas-de-control.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas (1).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-dinero (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verificar (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grafico-de-torta (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 264, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Inicio");
        jPBARRA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa (4).png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Inventario");
        jPBARRA.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ventas");
        jPBARRA.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Perdidas");
        jPBARRA.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Compras");
        jPBARRA.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Reportes");
        jPBARRA.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jPInven.setBackground(new java.awt.Color(215, 235, 235));

        javax.swing.GroupLayout jPInvenLayout = new javax.swing.GroupLayout(jPInven);
        jPInven.setLayout(jPInvenLayout);
        jPInvenLayout.setHorizontalGroup(
            jPInvenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPInvenLayout.setVerticalGroup(
            jPInvenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPBARRA.add(jPInven, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ajustes");
        jPBARRA.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/q3.png"))); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPBARRA.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 130));

        jPFONDO.add(jPBARRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 550));

        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio de Venta", "Precio de Compra"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPFONDO.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 470, 160));

        jPFONDO.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 110, -1));

        jComboBoxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProveedorActionPerformed(evt);
            }
        });
        jPFONDO.add(jComboBoxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 110, -1));

        jButton1.setBackground(new java.awt.Color(215, 235, 235));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPFONDO.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        jBAgregar.setBackground(new java.awt.Color(215, 235, 235));
        jBAgregar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBAgregar.setText("Actualizar Precio");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        jPFONDO.add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jPCatego.setBackground(new java.awt.Color(39, 77, 96));
        jPCatego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPCategoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria ");

        javax.swing.GroupLayout jPCategoLayout = new javax.swing.GroupLayout(jPCatego);
        jPCatego.setLayout(jPCategoLayout);
        jPCategoLayout.setHorizontalGroup(
            jPCategoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCategoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );
        jPCategoLayout.setVerticalGroup(
            jPCategoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCategoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPFONDO.add(jPCatego, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 20));

        jPProvedo.setBackground(new java.awt.Color(39, 77, 96));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Proveedor");

        javax.swing.GroupLayout jPProvedoLayout = new javax.swing.GroupLayout(jPProvedo);
        jPProvedo.setLayout(jPProvedoLayout);
        jPProvedoLayout.setHorizontalGroup(
            jPProvedoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProvedoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(22, 22, 22))
        );
        jPProvedoLayout.setVerticalGroup(
            jPProvedoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProvedoLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPFONDO.add(jPProvedo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        jPFONDO.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFecha.setBackground(new java.awt.Color(255, 255, 255));
        jLFecha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLFecha.setText("02/12/2024");
        jPanel1.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPFONDO.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 80, 20));

        jBAgregar1.setBackground(new java.awt.Color(215, 235, 235));
        jBAgregar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBAgregar1.setText("Agregar Proveedor");
        jBAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregar1ActionPerformed(evt);
            }
        });
        jPFONDO.add(jBAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        buttonGroup1.add(jRadioButtonProveedor);
        jPFONDO.add(jRadioButtonProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        buttonGroup1.add(jRadioButtonCategoria);
        jPFONDO.add(jRadioButtonCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jBAgregar2.setBackground(new java.awt.Color(215, 235, 235));
        jBAgregar2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBAgregar2.setText("Agregar Producto");
        jBAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregar2ActionPerformed(evt);
            }
        });
        jPFONDO.add(jBAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jBAgregar3.setBackground(new java.awt.Color(215, 235, 235));
        jBAgregar3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBAgregar3.setText("Agregar Categoria");
        jBAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregar3ActionPerformed(evt);
            }
        });
        jPFONDO.add(jBAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel19.setText("?");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 20, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Productos en Stock");
        jPFONDO.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Filtros de busqueda");
        jPFONDO.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void contruir_combo(ArrayList<String[]> lista, JComboBox combo) throws SQLException {
        for (String[] cat : lista) {
            combo.addItem(cat[1]);
        }
    }
    public void mostrar_tabla() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < productos.size(); i++) {
            String fila[] = productos.get(i);
            String fila2[] = {fila[0], fila[1], fila[2], fila[3], fila[4]};
            modelo.addRow(fila2);
        }
    }
    public int obtener_indice(ArrayList<String[]> lista, JComboBox seleccion) throws SQLException {
        int indice = 0;
        for (int i = 0; i < lista.size(); i++) {
            String fila[] = lista.get(i);
            if (fila[1].equals((String) seleccion.getSelectedItem())) {
                indice = Integer.parseInt(fila[0]);
            }
        }
        return indice;
    }
    public void buscar() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        if (jRadioButtonCategoria.isSelected()) {
            for (int i = 0; i < productos.size(); i++) {
                String fila[] = productos.get(i);
                if (fila[5].equals(obtener_indice(categoria, jComboBoxCategoria) + "")) {
                    String fila2[] = {fila[0], fila[1], fila[2], fila[3], fila[4]};
                    modelo.addRow(fila2);
                }
            }
        } else if (jRadioButtonProveedor.isSelected()) {
            for (int i = 0; i < productos.size(); i++) {
                String fila[] = productos.get(i);
                if (fila[6].equals(obtener_indice(provedor, jComboBoxProveedor) + "")) {
                    String fila2[] = {fila[0], fila[1], fila[2], fila[3], fila[4]};
                    modelo.addRow(fila2);

                }
            }
        }
    }


    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Inicio newframe = new Inicio();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Inventario newframe = new Inventario();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Ventas newframe = new Ventas();
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Perdidas newframe = new Perdidas();
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Comprar newframe = new Comprar();
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Reportes newframe = new Reportes();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cmensaje.mensaje("Busqueda exitosa");
        try {
            buscar();
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        Actualizar newframe = new Actualizar();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Ajuste newframe = new Ajuste();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jPCategoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPCategoMouseClicked
        //AQUI
    }//GEN-LAST:event_jPCategoMouseClicked

    private void jBAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregar1ActionPerformed
        // TODO add your handling code here:
        Proveedor newframe = new Proveedor();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBAgregar1ActionPerformed

    private void jComboBoxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProveedorActionPerformed

    private void jBAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregar2ActionPerformed
        // TODO add your handling code here:
        AgregarProducto newframe = new AgregarProducto();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBAgregar2ActionPerformed

    private void jBAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregar3ActionPerformed
        // TODO add your handling code here:
        Categoria newframe = new Categoria();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBAgregar3ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        cmensaje.mensaje("Si tienes alguna duda con tu inicio, "
            + "puede checar el manual de usuario, punto 2.-Inventario");
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBAgregar1;
    private javax.swing.JButton jBAgregar2;
    private javax.swing.JButton jBAgregar3;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxProveedor;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBARRA;
    private javax.swing.JPanel jPCatego;
    private javax.swing.JPanel jPFONDO;
    private javax.swing.JPanel jPInven;
    private javax.swing.JPanel jPProvedo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCategoria;
    private javax.swing.JRadioButton jRadioButtonProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
