/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Programa creado por Isaac Yahel Luna Hernandez
package Tienda;

import java.awt.Color;
import java.util.ArrayList;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

public class Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Proveedor
     */
    //*************************Parametros**********************************//
//***********************************************************//
    Mensajes cmensaje = new Mensajes();
    Operaciones opera = new Operaciones();
    Ajuste aju = new Ajuste();
    Inventario inventario = new Inventario();
    Color PanelOpcionColor;
    Color FondoOpcionColor;
    Color colorpordefectofondo = new Color(215, 235, 235);
    Color colorpordefectobarra = new Color(39, 77, 96);

    ArrayList<String[]> productos = new ArrayList<>();
    ArrayList<String[]> categoria = new ArrayList<>();
    ArrayList<String[]> provedor = new ArrayList<>();
    int id=0;
//**************************Fin de parametros*********************************//
//***********************************************************//
    public Proveedor() {
        initComponents();
        this.setLocationRelativeTo(null);
        PanelOpcionColor = aju.mandarfechaycolores(2);
        FondoOpcionColor = aju.mandarfechaycolores(3);
        jBBarra.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);

        try {
            productos = opera.Consultar(6);
            categoria = opera.Consultar(0);
            
        } catch (SQLException ex) {
            Logger.getLogger(AgregarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFONDO = new javax.swing.JPanel();
        jTextNombre = new javax.swing.JTextField();
        jBBarra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPFONDO.setBackground(new java.awt.Color(215, 235, 235));
        jPFONDO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPFONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jPFONDO.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 250, -1));

        jBBarra.setBackground(new java.awt.Color(39, 77, 96));
        jBBarra.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBBarra.setForeground(new java.awt.Color(255, 255, 255));
        jBBarra.setText("Añadir Proveedor");
        jBBarra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jBBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBarraActionPerformed(evt);
            }
        });
        jPFONDO.add(jBBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 230, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nuevo Proveedor");
        jPFONDO.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 170, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-retroceso.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre:");
        jPFONDO.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPFONDO, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jBBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBarraActionPerformed
        try {
            provedor = opera.Consultar(7);
        } catch (SQLException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!jTextNombre.getText().trim().isEmpty()) {
            boolean isDuplicate = false;
            
            // Comprobar duplicados
            for (String[] fila : provedor) {
                if (jTextNombre.getText().trim().equalsIgnoreCase(fila[1])) {
                    isDuplicate = true;
                    break;
                }
            }

            if (isDuplicate) {
                cmensaje.mensaje_error("Error, proveedor duplicado");
            } else {
                // Confirmar antes de proceder
                if (cmensaje.mensaje_confirmacion("¿Está seguro de continuar con la acción?", "Realizando acción", "Acción cancelada")) {
                    try {
                        // Insertar nuevo proveedor
                        opera.Insertar(provedor, "proveedor", jTextNombre.getText().trim());
                        cmensaje.mensaje("Registro exitoso");
                        jTextNombre.setText(""); // Limpiar campo de texto
                    } catch (SQLException ex) {
                        Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
                        cmensaje.mensaje_error("Error al registrar el proveedor. Intente nuevamente.");
                    }
                } else {
                    cmensaje.mensaje_error("Acción cancelada");
                }
            }
        } else {
            cmensaje.mensaje_error("Error, el nombre del proveedor no puede estar vacío.");
        }

    }//GEN-LAST:event_jBBarraActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Inventario newframe = new Inventario();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBarra;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPFONDO;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
