/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Programa creado por Isaac Yahel Luna Hernandez
package Tienda;

import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivanvalle_
 */
public class Ventas extends javax.swing.JFrame {
//*************************Parametros**********************************//
//***********************************************************//
//============================================================================================
    //                                                     INICIO DE PARAMETROS
    //============================================================================================  

    ArrayList<String[]> cuenta = new ArrayList<>();
    Operaciones opera = new Operaciones();

    Mensajes cmensaje = new Mensajes();
    Ajuste aju = new Ajuste();
    String color;
    Color PanelOpcionColor;
    Color FondoOpcionColor;
    Color colorpordefectofondo = new Color(215, 235, 235);
    Color colorpordefectobarra = new Color(39, 77, 96);
    String usuario;
    //============================================================================================
    //                                                     FIN PARAMETROS
    //============================================================================================  

//**************************Fin de parametros*********************************//
//***********************************************************//
    /**
     * Creates new form Ven
     */
    public Ventas() {
        initComponents();
        try {
            usuario = opera.conseguir_color(3);
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
        PanelOpcionColor = aju.mandarfechaycolores(2);
        FondoOpcionColor = aju.mandarfechaycolores(3);
        jPBARRA.setBackground(PanelOpcionColor);
        jPFONDO.setBackground(FondoOpcionColor);
        jPVenta.setBackground(FondoOpcionColor);
        jPanel1.setBackground(PanelOpcionColor);
        this.setLocationRelativeTo(null);
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Formatear la fecha
        String fecha = fechaActual.format(formato);
        jLFecha.setText(fecha + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFONDO = new javax.swing.JPanel();
        jPBARRA = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPVenta = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBOK = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLFecha = new javax.swing.JLabel();
        jBConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPFONDO.setBackground(new java.awt.Color(215, 235, 235));
        jPFONDO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPFONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBARRA.setBackground(new java.awt.Color(39, 77, 96));
        jPBARRA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas-de-verificacion.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-dinero (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verificar (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grafico-de-torta (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 264, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Inicio");
        jPBARRA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa (4).png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inventario");
        jPBARRA.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Perdidas");
        jPBARRA.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Compras");
        jPBARRA.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ajustes");
        jPBARRA.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jPVenta.setBackground(new java.awt.Color(215, 235, 235));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setText("Ventas");

        javax.swing.GroupLayout jPVentaLayout = new javax.swing.GroupLayout(jPVenta);
        jPVenta.setLayout(jPVentaLayout);
        jPVentaLayout.setHorizontalGroup(
            jPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVentaLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(36, 36, 36))
        );
        jPVentaLayout.setVerticalGroup(
            jPVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVentaLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jPBARRA.add(jPVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPBARRA.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Reportes");
        jPBARRA.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/q3.png"))); // NOI18N
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPBARRA.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 130));

        jPFONDO.add(jPBARRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 550));

        jTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigoActionPerformed(evt);
            }
        });
        jPFONDO.add(jTCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 60, 280, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Registro de Ventas");
        jPFONDO.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jBOK.setBackground(new java.awt.Color(215, 235, 235));
        jBOK.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBOK.setText("Añadir");
        jBOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBOKMouseClicked(evt);
            }
        });
        jBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOKActionPerformed(evt);
            }
        });
        jPFONDO.add(jBOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        jBActualizar.setBackground(new java.awt.Color(215, 235, 235));
        jBActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBActualizar.setText("Actualizar");
        jBActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBActualizarMouseClicked(evt);
            }
        });
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });
        jPFONDO.add(jBActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel9.setText("Total");
        jPFONDO.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        jLTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLTotal.setText(".");
        jPFONDO.add(jLTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 270, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/procesamiento-de-datos.png"))); // NOI18N
        jPFONDO.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jBEliminar.setBackground(new java.awt.Color(215, 235, 235));
        jBEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBEliminar.setText("Eliminar Producto");
        jBEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBEliminarMouseClicked(evt);
            }
        });
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPFONDO.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 180, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFecha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLFecha.setText("02/12/2024");
        jPanel1.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPFONDO.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 80, 20));

        jBConfirmar.setBackground(new java.awt.Color(215, 235, 235));
        jBConfirmar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBConfirmar.setText("Confirmar Venta");
        jBConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBConfirmarMouseClicked(evt);
            }
        });
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });
        jPFONDO.add(jBConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 180, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPFONDO.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 430, 200));

        jLabel20.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel20.setText("?");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPFONDO.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 20, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                              Clase Principal
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//

    public void clasePrincipal() {

    }

    public ArrayList<String[]> crear_tabla(ArrayList<String[]> datos) throws SQLException {

        datos = opera.Consultar(6);
        return datos;
    }

    public int mandar_total(JLabel totales, ArrayList<String[]> cuenta) {
        int total = 0;
        for (int i = 0; i < cuenta.size(); i++) {
            String fila[] = cuenta.get(i);
            total += Integer.parseInt(fila[3]);
        }
        totales.setText("$" + total);
        System.out.println("total:" + total);
        return total;
    }

    public void transaccion(int opcion, JTable tabla, String codigo, ArrayList<String[]> cuenta, JLabel totales) throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        ArrayList<String[]> productos = new ArrayList<>();
        productos = crear_tabla(productos);

        for (String[] producto : productos) {
            if (codigo.equals(producto[0])) {
                boolean repeticion = true;
                for (int i = 0; i < tabla.getRowCount(); i++) {
                    if (producto[1].equals((String) modelo.getValueAt(i, 0))) {
                        repeticion = false;
                    }
                }
                if (repeticion) {

                    int total = 1 * Integer.parseInt(producto[opcion]);
                    String[] datos = {producto[1], 1 + "", producto[opcion], total + ""};
                    modelo.addRow(datos);
                    cuenta.add(datos);
                }
            }
        }
        tabla.setModel(modelo);
        mandar_total(totales, cuenta);
    }

    public void actualizar(ArrayList<String[]> cuenta, JTable tabla, JLabel totales) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

        // Verificar que las filas en la tabla y en la lista sean iguales
        if (modelo.getRowCount() != cuenta.size()) {
            throw new IllegalArgumentException("La cantidad de filas en la tabla y en la lista no coincide.");
        }

        for (int i = 0; i < cuenta.size(); i++) {
            String[] fila = cuenta.get(i);
            Object cantidadObj = modelo.getValueAt(i, 1);
            Object precioObj = modelo.getValueAt(i, 2);

            // Validar si los valores no son nulos
            if (cantidadObj == null || precioObj == null) {
                continue; // Saltar esta fila si hay valores nulos
            }

            try {
                int cantidad = Integer.parseInt(cantidadObj.toString());
                int precio = Integer.parseInt(precioObj.toString());

                // Validar si los valores son negativos
                if (cantidad < 0 || precio < 0) {
                    cmensaje.mensaje_error("Error: Los valores no pueden ser negativos.");
                    continue;
                }

                // Si la cantidad cambió, recalcular el valor total
                if (cantidad != Integer.parseInt(fila[1])) {
                    int valor = cantidad * precio;
                    modelo.setValueAt(valor, i, 3); // Actualizar tabla
                    fila[1] = String.valueOf(cantidad); // Actualizar lista
                    fila[3] = String.valueOf(valor);   // Actualizar lista
                    cuenta.set(i, fila);               // Guardar cambios en la lista
                }
            } catch (NumberFormatException e) {
                cmensaje.mensaje_error("Error verifique la cantidad");
            }
        }

        // Actualizar totales
        mandar_total(totales, cuenta);
    }

    public void eliminar(JTable tabla, ArrayList<String[]> cuenta, JLabel totales) {
        // Verificar si hay selección en la JTable
        int selectedRow = tabla.getSelectedRow();       // Índice de fila seleccionada

        if (selectedRow == -1) {
            cmensaje.mensaje_error("No se ha seleccionado ningun producto");
        } else {
            // No se ha seleccionado ninguna fila o columna
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            cuenta.remove(tabla.getSelectedRow());
            modelo.removeRow(tabla.getSelectedRow());
            actualizar(cuenta, tabla, totales);

        }

    }
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                              Fin Clase Principal
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Inicio newframe = new Inicio();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Inventario newframe = new Inventario();
        
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Ventas newframe = new Ventas();
        
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Perdidas newframe = new Perdidas();
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Comprar newframe = new Comprar();
        if(aju.contraseña(newframe)== true){
            dispose();   
        }
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Reportes newframe = new Reportes();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOKActionPerformed
        cmensaje.mensaje("Producto añadido");
        try {
            transaccion(3, jTable1, jTCodigo.getText(), cuenta, jLTotal);
            jTCodigo.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBOKActionPerformed

    private void jTCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodigoActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        cmensaje.mensaje("Tabla actualizada");
        actualizar(cuenta, jTable1, jLTotal);
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        cmensaje.mensaje_confirmacion("¿Estás seguro de elminar este producto del registro?", "Accion Confirmada", "Accion fallida");

        eliminar(jTable1, cuenta, jLTotal);
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Ajuste newframe = new Ajuste();
        newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
        actualizar(cuenta, jTable1, jLTotal);
        if (cmensaje.mensaje_confirmacion("¿Estás seguro de confirmar esta venta?", "Venta confirmada", "Venta fallida")) {
            // TODO add your handling code here:
            try {
                boolean producto_descontado = true;
                ArrayList<String[]> productos = opera.Consultar(6); // Lista de productos en stock
                StringBuilder errores = new StringBuilder();       // Para acumular errores
                for (String[] fila : cuenta) {                     // Recorrer productos en cuenta
                    boolean encontrado = false;
                    for (String[] prod : productos) {
                        if (fila[0].equals(prod[1])) { // Comparar códigos o identificadores
                            encontrado = true;
                            int stockActual = Integer.parseInt(prod[2]);
                            int cantidadSolicitada = Integer.parseInt(fila[1]);
                            if (stockActual <= 0 || stockActual - cantidadSolicitada < 0) {
                                errores.append("Error: No hay suficiente stock de ")
                                        .append(prod[1])
                                        .append(". Stock actual: ")
                                        .append(stockActual)
                                        .append(", solicitado: ")
                                        .append(cantidadSolicitada)
                                        .append(".\n");
                                producto_descontado = false;
                            }
                            break; // Producto encontrado, salir del bucle
                        }
                    }
                    if (!encontrado) {
                        errores.append("Error: Producto no encontrado en stock: ")
                                .append(fila[0])
                                .append(".\n");
                        producto_descontado = false;
                    }
                }

// Mostrar errores acumulados si los hay
                if (errores.length() > 0) {
                    cmensaje.mensaje_error(errores.toString());
                }

                if (producto_descontado) {
                    cmensaje.mensaje("Venta realizada");
                    opera.Insertar_venta("venta", cuenta, mandar_total(jLTotal, cuenta));
                    Ventas newframe = new Ventas();
                    newframe.setVisible(true);
                    dispose();

                }
            } catch (SQLException ex) {
                Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jBOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBOKMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jBOKMouseClicked

    private void jBActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jBActualizarMouseClicked

    private void jBEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jBEliminarMouseClicked

    private void jBConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConfirmarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jBConfirmarMouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        cmensaje.mensaje("Si tienes alguna duda con tu inicio, "
                + "puede checar el manual de usuario, punto 3.-Venta");
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBOK;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBARRA;
    private javax.swing.JPanel jPFONDO;
    private javax.swing.JPanel jPVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
